name: Execution tests
on: [push]

defaults:
  run:
    shell: bash
jobs:
  gitwatch-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install tools
        run: |
          sudo apt-get -install y inotify-tools
          sudo apt-get -y install bats
      - name: Run the tests
        run: |
          git config --global user.email "test@email.com"
          git config --global user.name "test user"
          bats tests
